[package]
name = "bevy-dynamic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ['bevy/dynamic_linking']

[dependencies]
bevy = "0.11.3"
rand = "0.8.5"
