name: rust build & release

on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    name: build executables
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ github.ref || github.run_id }}
      - name: Install windows target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - name: Install build dependencies
        run: sudo apt-get update; sudo apt-get install libasound2-dev libudev-dev gcc-mingw-w64-x86-64
      - name: Build Linux Executable
        run: cargo build --verbose --release --no-default-features
      - name: Build Windows Executable
        run: cargo build --verbose --target=x86_64-pc-windows-gnu --release --no-default-features
      - name: Release binary to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
              target/x86_64-pc-windows-gnu/release/bevy-dynamic.exe
              target/release/bevy-dynamic
