name: rust build & release

on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build-linux:
    name: build linux executable
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: sudo apt-get update; sudo apt-get install libasound2-dev libudev-dev lld
      - name: Build Linux Executable
        run: cargo build --verbose --release --no-default-features
      - name: prepare linux release
        run: mkdir linux-release; mv target/release/bevy-dynamic linux-release/; cp assets linux-release/assets -r
      - name: zip linux release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          filename: 'linux_x86-64.zip'
          path: linux-release/*
      - name: Release binary to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux_x86-64.zip
  build-windows:
    name: build windows executable
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install windows target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - name: Install build dependencies
        run: sudo apt-get update; sudo apt-get install libasound2-dev libudev-dev gcc-mingw-w64-x86-64 lld
      - name: Build Windows Executable
        run: cargo build --verbose --target=x86_64-pc-windows-gnu --release --no-default-features
      - name: prepare windows release
        run: mkdir windows-release; mv target/x86_64-pc-windows-gnu/release/bevy-dynamic.exe windows-release/; cp assets windows-release/assets -r
      - name: zip windows release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          filename: 'windows_x86-64.zip'
          path: windows-release/*
      - name: Release binary to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows_x86-64.zip
